nsf/termbox-go

terminfo.go

I've just added an entry for [suckless's simple terminal](http://st.suckless.org/) in terminfo. St tries to be xterm compatible, but I don't think it's fully there yet. I have tested the demos and they work.

Added support for st

---

_demos/interrupt.go
api.go
api_common.go
api_windows.go
termbox.go
termbox_windows.go

This event is sent whenever termbox-go is exiting.  This allows a proper
shutdown of an event loop to occur, since it will loop forever otherwise
(even after calling `termbox.Close()`).

Add EventShutdown event

---

api.go
api_windows.go
termbox_windows.go

Fix cjk width

---

README.md

[Hecate](https://github.com/evanmiller/hecate) is a hex editor/viewer that makes heavy use of termbox-go. Thanks for a great library!

Fix typo, add Hecate to examples, alphabetize

---

README.md

Adds [termloop](https://github.com/JoelOtter/termloop) as an example project.

Add example project

---

api.go
termbox.go

В режиме OutputGrayscale невозможно вывести в консоль чистый белый и чистый черный цвет, поскольку этот диапазон палитры xterm начинается от очень-темно-серого и заканчивается очень-светло-серым. Если добавить к этому градиенту цвет 17 (черный) и 232 (белый), тогда получится полноценный градиент от черного до белого.
Это, конечно, легко реализовывается собственными силами, но раз уж в библиотеке вводится искусственный режим вывода, реализующий монохромные цвета палитры xterm, тогда он должен включать и черный и белый цвет.
Если рассматривать тембокс в отрыве от консоли, тогда вообще в этом режиме нет ни какого смысла, поскольку тогда пользователь самостоятельно задает цветовую палитру и каждому индексу волен назначать необходимый цвет.
На тех, кто использовал этот режим раньше это …

expand grayscale

---

api_windows.go

`termbox.Close()` hanged up when `input_comm` channel is not polled.
Example Code:
```go
package main
import "github.com/nsf/termbox-go"
import "time"
func main() {
termbox.Init()
time.Sleep(1000 * time.Millisecond)
termbox.Close()
}
```
Result:
```console
>go run test.go
fatal error: all goroutines are asleep - deadlock!
goroutine 1 [chan receive]:
github.com/nsf/termbox-go.Close()
src/github.com/nsf/termbox-go/api_windows.go:83 +0x95
main.main()
src/test.go:9 +0x31
goroutine 4 [chan send]:
github.com/nsf/termbox-go.input_event_producer()
src/github.com/nsf/termbox-go/termbox_windows.go:782 +0x4f4
created by github.com/nsf/termbox-go.Init
src/github.com/nsf/termbox-go/api_windows.go:68 +0x4ac
exit status 2
```

Fix hang with termbox.Close() on Windows

---

syscalls_darwin.go

Sorry, my previous https://github.com/nsf/termbox-go/commit/c4d5eeeb18b378c361f9f2a731680e8b835969ed commit to fix the issue actually broke the darwin/amd64. I misinterpreted how the Go build constraint works and the one without the architecture prefix is being build even for the `amd64` architecture. This follow up PR adds a build flag to the more generic `syscalls_darwin.go` file to exclude `amd64`. Sorry for the screw up!

Fix accidental too-relaxed build constraint

---

README.md

gocui is a project built up on top of termbox-go that helps you create
console user interfaces.

Added gocui to the projects list

---

termbox_windows.go

It would appear 256 colours are not supported on Windows. This is expected, but in some cases a program written for 256 colours will crash when run on Windows. This change prevents the out-of-bounds error when looking up the colour tables.
Personally, I think displaying incorrect colours is a more desirable behaviour than just crashing. Termbox is really good at compatibility and I think this helps that out a little bit.
More details for this are available in the Termloop issue [#24](https://github.com/JoelOtter/termloop/issues/24).

Prevent out-of-bounds error with 256 colours on Windows

---

_demos/editbox.go

A demo code of editbox.go is not working when user inputs multi-byte characters(ex.Japanese) to it.
I fixed it.

Fix display when input multi-byte characters

---

README.md

Hi,
I created this little hack to paint images in the terminal, which could not have happened without the awesome termbox-go. I wonder if you would like to add it to the examples list?

Add pxl to examples list

---

README.md

This PR adds the gone pomodoro timer to the list of projects using termbox.

Add gone a cli pomodoro® timer

---

api.go

`api.go` contained this line as a safeguard against coding mistakes. Unfortunately, because it was unreachable code, it flunked `go vet`. I think `go vet` is a better safeguard against bugs than this line, so I propose removing it. With this line removed, `termbox-go` is 100% clean in `go vet`.

Remove panic("unreachable") which flunks `go vet`

---

termbox.go

This was caught by [`gosimple`](https://github.com/dominikh/go-simple). With this PR, `termbox-go` is 100% clean in `gosimple`.

Replace `if err != nil { return err } return nil' with 'return err'

---

README.md

I've created a CLI tool for easily viewing prettified JSON, using termbox-go.
I really enjoyed working with termbox-go! Thanks for the great work :)

Add 'jv' as an example in README

---

README.md

I've created a CLI tool for monitoring numerous hosts easily, using termbox-go.
I am happy if you add pinger to examples!

Add 'pinger' as an example in README

---

api.go
escwait.go
escwait_darwin.go
termbox.go

This proposed solution to the macOS partial escape sequence problem can be contrasted against #158 (which is similar to another proposal from the comment thread on #132). Compared with that solution, this one is more complicated but will handle the case where an escape sequence is interrupted such that ONLY the escape character comes through ahead of the rest of the sequence. It's not proven whether that's possible since AFAICT we don't understand the mechanism by which the escape sequences are being split up in macOS, but then the whole problem here is nondeterminism. 
Also this solution relies on an arbitrary delay which works according to my testing but is not verifiably "correct". This causes an short delay in processing of plain Escape keypresses. The delay is supposed to be long …

macOS delay on incomplete escape sequences to avoid spurious escape keypress detection #132

---

api.go

Sorry to dredge this up again but I just noticed I can still reproduce the spurious escape keypress issue on macOS with rapidly repeated mouse wheel scroll events. Of course we don't understand what's driving the timing here so there is no perfect fix, but doubling the wait time seems to prevent any further problems in my use case. Hopefully this is good enough because I don't think I'd want to go too much higher than 100 ms -- at some point the user could start noticing the delay before a real escape keypress is registered.
@nsf is this change OK with you?

Double the macOS escape sequence wait period after encounting spurious escape keypresses with rapid scroll events

---

termbox_windows.go

Within PR #168 a query about the minimum size of Windows windows was implemented which should fix the problem of issue #153. But as described in https://msdn.microsoft.com/library/windows/desktop/ms724385, the implemented function provides the minimum size in pixels. 
The first commit implements the WinAPI GetCurrentConsoleFont which allows to query the size of a character within the console. This allows the required rows and columns to be calculated to meet the minimum size of the window. Currently, whole rows and columns of the console are used for the minimum size instead of pixels, which can lead to display errors like issue #183.
The second commit fixes another display error. If the height of the console window is increased once in Windows, the buffer height is set to the same size. …

Fix windows size/resize problems (and also #183)

---

terminfo.go

The debian package of ncurses searches `/lib/terminfo` before searching
`/usr/share/terminfo`.
See https://github.com/mirror/ncurses/blob/master/package/debian/rules#L83
This addresses issue https://github.com/nsf/termbox-go/issues/155

Add /lib/terminfo to terminfo search path.

---

README.md

I created a surprisingly fun touch-typing tutor that implements the method described in Steve Yegge's [classic post on touch typing](http://steve-yegge.blogspot.de/2008/09/programmings-dirtiest-little-secret.html). Would love to have it listed under examples!

Add gotypist to examples

---

api_windows.go
termbox_windows.go

This PR fixes two bugs:
1. Earlier code was not clearing the screen fully and the fix for that is in first commit.
2. The other issue is more intricate, it was causing termbox to paint content in invisible portion of console.
This issue only happens when you launch termbox application when existing console buffer is scrolled down. See attached screenshot (#1) and (#2). With the fix, the problem goes away and console is painted correctly as we fix the window position by calling SetConsoleWindowInfo.

Fix two bugs in Windows console handling

---

api_windows.go
termbox_windows.go

This ensures that outer console window is correctly resized.
The issue is shown below and described below the picture.
If you have a console window (on windows 10) with vertical scroll bar (Picture#1 from left), then first calling SetConsoleWindowInfo and then calling SetConsoleScreenBufferSize results in empty space (shown in picture #2 with red rectangle).
The correct way is to reverse these i.e. first change ScreenBufferSize and then the window size. The update_size_maybe() function had the right change, but I missed this in Init() in my previous commit. The picture #3 shows that with this PR, we get the console window size change correctly.

Reorder SetConsoleScreenBufferSize and SetConsoleWindowInfo.

---

api_windows.go

On Windows 10, WriteConsoleOutputW break compatibility. When writing three unicode characters, the character is displayed overlayed with 3 cells.
```c
#include <windows.h>
#include <stdio.h>
int
main(int argc, char* argv[]) {
HANDLE h = GetStdHandle(STD_OUTPUT_HANDLE);
CHAR_INFO ci[3] = {};
COORD buffer_size = { 3, 1 };
COORD start_coord = { 0, 0 };
SMALL_RECT sr = { 0, 0, 80, 25 };
SHORT white = FOREGROUND_BLUE | FOREGROUND_GREEN | FOREGROUND_RED;
ci[0].Char.UnicodeChar = L'あ';
ci[0].Attributes = white;
ci[1].Char.UnicodeChar = L'い';
ci[1].Attributes = white;
ci[2].Char.UnicodeChar = L'う';
ci[2].Attributes = white;
WriteConsoleOutputW(h, (CHAR_INFO*)ci, buffer_size, start_coord, &sr);	
return 0;
}
```
Currently, all of products using termbox-go does not work correctly with wide …

Fix multibyte-strings

---

README.md

There are a number of projects mentioned in the README that have since then moved to `tcell`.
On the other hand, there are still numerous (although little) projects that still use `termbox`.
If you say, you don't have the time to maintain `termbox` anymore, how would you feel about someone else taking over the project and having a take at the open issues or do you think there is really no point in doing anymore to `termbox`?

Removed tcell projects from the README, future of termbox

---

api_windows.go

https://docs.microsoft.com/en-us/windows/console/reading-and-writing-blocks-of-characters-and-attributes
https://docs.microsoft.com/en-us/windows/console/char-info-str
In latest cmd.exe, multi-byte strings must be handled with attributes of COMMON_LVB_XXX.

Fix rendering of multi-byte strings

---

termbox.go
terminfo_builtin.go
terminfo_builtin_test.go

In recent commits
- a08d44e997 implemented dim, blink hidden
- b53f34a171 extra attributes wip
3 more attributes were added - hidden, dim and cursive.
Unfortunately these commits didn't adjust the builtin terminfo.
This leads to crashes which look like this on quit
panic: runtime error: index out of range [14] with length 14
goroutine 1 [running]:
github.com/nsf/termbox-go.Close()
github.com/nsf/termbox-go@v1.1.0/api.go:146 +0x458
And other odd behaviour like arrow keys not being recognised.
This patch fixes the terminfo, and names all the entries to make it
easier to update. It also adds a test to make sure the terminfo
doesn't get out of sync again.
See: https://github.com/rclone/rclone/issues/5259

Fix crashes and odd behaviour due to builtin terminfo inconsistencies

---

api.go
termbox.go

On FreeBSD and OpenBSD, the `syscall.Read` call in the anonymous goroutine in `Init` blocks.  This causes problems during `Close`: the send to the `quit` channel blocks, because the anonymous goroutine is blocked on `syscall.Read`, and things remain blocked until `syscall.Read` returns.
`Init` sets the `in` file descriptor to nonblocking with `fcntl`, but—on FreeBSD and OpenBSD—the `in` fd and the `out` fd are the same, and every `out.Fd` call [clears nonblocking flag](https://github.com/golang/go/blob/f229e7031a6efb2f23241b5da000c3b3203081d6/src/os/file_unix.go#L85).  This problem can be fixed by saving the `out.Fd` in a variable prior to setting the `in` fd to nonblocking, and using that variable afterward instead of `out.Fd`.
https://github.com/nsf/termbox-go/issues/167 is related. …

Fix nonblocking read on BSD systems
